name: Markdown to HTML Converter

on:
  push:
    paths:
      - 'converter_markdown/input_folder_markdown/**/*.md'

# Global permissions for all jobs
permissions:
  contents: write  # Needed for pushing changes

# Environment variables
env:
  PYTHONUNBUFFERED: "1"
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  convert-markdown:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai python-dotenv
    
    - name: Create output directory
      run: mkdir -p converter_markdown/output_folder_markdown
    
    - name: Run markdown converter
      run: |
        python converter_markdown/md_to_html_converter.py
    
    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    
    - name: Stage and commit changes
      run: |
        # Debug: List generated files
        echo "Checking for generated files:"
        ls -la converter_markdown/output_folder_markdown/ || echo "No files generated"
        
        # Add generated HTML files
        git add converter_markdown/output_folder_markdown/
        
        # Debug: Check git status
        echo "Git status:"
        git status
        
        # Commit if changes are detected
        git diff --quiet && git diff --staged --quiet || (
          echo "Changes detected. Committing..." &&
          git commit -m "chore: Convert markdown to HTML [skip ci]
          
          - Generated HTML files from markdown
          - Auto-generated by GitHub Actions" &&
          
          # Set remote URL with token for authentication
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} &&
          
          # Push changes
          echo "Pushing changes to branch: ${{ github.ref_name }}" &&
          git push origin HEAD:${{ github.ref_name }}
        ) 