name: Handle File Uploads

on:
  pull_request:
    types: [opened]

jobs:
  process-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Debug PR Info
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Body: ${{ github.event.pull_request.body }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Head Ref: ${{ github.head_ref }}"
          echo "PR Base Ref: ${{ github.base_ref }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process uploaded files
        run: |
          # Create input directory if it doesn't exist
          mkdir -p converter_markdown/input_folder_markdown
          
          # List all files in the repository
          echo "Current directory structure:"
          find . -type f
          
          # Move any .md files to the input directory
          find . -name "*.md" -not -path "./converter_markdown/input_folder_markdown/*" -exec mv {} converter_markdown/input_folder_markdown/ \;
          
          # Add and commit changes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add converter_markdown/input_folder_markdown/
          git commit -m "Add uploaded files"
          git push

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Files have been processed and added to the repository. The pull request will be automatically merged.'
            })

      - name: Merge PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'
            }) 